### PR TITLE
ADOP Pluggable SCM documentation

### PR DESCRIPTION
**Pull request by kristapsm**

### CODE REVIEW

**Comment by nickdgriffin** [comment]
Hi Kristaps,

Great stuff!

Can I request a couple of minor tweaks to this please?

- Remove "recipes" from the directory structure
- The README.md under site/ should be for generating the documentation site and can therefore be mostly copied from adop-docker-compose - with the addition of how to generate the javadocs please
- Remove the Windows line endings from the files that have them
- Squash the commits

Thanks,
Nick

**Comment by kristapsm** [comment]
Hi Nick,

I have made all the changes and pushed to repo.
Not sure if commits are squashed as with git rebase I was able to only change my latest commit.

Regards,
Kristaps

**Comment by nickdgriffin** [comment]
You'll need to do an interactive rebase on the commit before your first commit in this PR, and that will show you all of your commits to squash.

**Comment by kristapsm** [comment]
Hi Nick,

I have squashed my commits into one.

Regards,
Kristaps

**Comment by nickdgriffin** [comment]
Great, thanks!

LGTM.

**Pull request merged**
